version: "3.9"
services:
  db:
    image: mongo:latest
    ports:
      - "27017:27017"
    env_file:
      - ./mongodb-auth.env
    volumes:
      - mongodb-data:/data/db

  registersystem-backend:
    image: lacribeiro11/registersystem-backend:latest
    env_file:
      - ./mongodb.env
    ports:
      - "8080:8080"

volumes:
  mongodb-data:
